<script src="<?php echo \Http\View\Tpl::getJsBaseUrl();?>lib/seajs/1.3.1/sea.js"></script>
<?php if(ENV=='dev'): ?>
<script src="<?php echo \Http\View\Tpl::getJsBaseUrl();?>rootConfig.js"></script>
<?php elseif($view->js_debug): ?>
<script src="<?php echo \Http\View\Tpl::getJsBaseUrl();?>app/all-debug.js"></script>
<?php else: ?>
<script src="<?php echo \Http\View\Tpl::getJsBaseUrl();?>app/all.js"></script>
<?php endif; ?>

<?php

if(!empty($view->js_config)){
    $js_config = Common\String\Encode::json($view->js_config);
    echo "<script>var js_config={$js_config}</script>\n";
}

if(!empty($view->page_js)){
    if (ENV == 'dev'){
        echo "<script>seajs.use('{$view->page_js}');</script>\n";
    }else if($view->js_debug) {
        echo "<script>seajs.use('{$view->page_js}-debug');</script>\n";
    }else{
        echo "<script>seajs.use('{$view->page_js}');</script>\n";
    }
}


?>
</body>
</html>