<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo $title; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- build:xcss ../../css/all.css -->
    <?php
        if(isset($page_css)){
            \Http\View\Tpl::loadCss($page_css);
        }
    ?>
    <!-- /build -->
</head>
<body>