<?php
    Helper_Tpl::loadView('comm/header.phtml', array(
        'title'=>'首页',
        'page_css'=>array(
            'login.css'
        )
    ));
?>
<div >
<form id="form_login" method="post" action="#">
    <div><strong>用户名:</strong><input type="text" name="username" placeholder="请输入用户名"/></div>
    <div><strong>密码:</strong><input type="password" name="password" placeholder="请输入密码"/></div>
    <div>
        <strong>验证码:</strong><input type="text" name="vcode" placeholder="请输入密码"/>
        <img id="vcode_image" src="/account/vcode"  width="75" height="20"  alt="验证码"  align="bottom" style="cursor:pointer;" title="看不清可单击图片刷新" " />
    </div>
   
    <div id="error">用户名或密码错误</div>
    <div><input action-type="login" type="submit" value="登录"/></div>
    
</form>
</div>
<?php
    Helper_Tpl::loadView('comm/footer.phtml', array(
        'title'=>'首页',
        'page_js'=>array('account.js'),
    ));
?>