<?php
    \Http\View\Tpl::loadView('comm/header.phtml', array(
        'title'=>'注册',
        'page_css'=>array(
            'all.css'
        )
    ));
?>
<div >
    
<form id="register_form" method="post" action="#">
    <div><strong>用户名:</strong><input type="text" name="username" placeholder="请输入用户名"/></div>
    <div><strong>邮箱:</strong><input type="text" name="email" placeholder="邮箱"/></div>
    <div>
        <fieldset>
            <legend>性别</legend>
            <label for="gender_male">
                <input type="radio" id="gender_male" value="m" name="gender" required>男
            </label>
            <label for="gender_female">
                <input type="radio" id="gender_female" value="f" name="gender">女
            </label>
            <label for="gender" class="error">请选择性别</label>
        </fieldset>
    </div>
    <div><strong>密码:</strong><input type="password" name="password" placeholder="请输入密码"/></div>
    <div><strong>确认密码:</strong><input type="password" name="password_confirm" placeholder="确认密码"/></div>
    <div>
            <label for="accept_rule">
                <input type="checkbox" class="checkbox" id="accept_rule" value="1" name="accept_rule" required>我已经阅读注册须知
            </label>
    </div>
    <div>
        <strong>验证码:</strong><input type="text" name="vcode" placeholder="请输入密码"/>
        <img id="vcode_image" src="/account/vcode"  width="75" height="20"  alt="验证码"  align="bottom" style="cursor:pointer;" title="看不清可单击图片刷新" " />
    </div>
    <div><input action-type="login" type="submit" value="登录"/></div>
</form>
</div>
<?php
    \Http\View\Tpl::loadView('comm/footer.phtml', [], $this);
    //加载js代码
    //\Http\View\Tpl::loadJs(['a.js']);
?>
