<?php
    \Http\View\Tpl::loadView('comm/header.phtml', array(
        'title'=>'注册',
        'page_css'=>array(
            'all.css'
        )
    ));
?>
<div >
    
<form id="register_form" method="post" action="#">
    <fieldset>
        <legend>请填写如下内容</legend>
        <div><strong>用户名:</strong><input type="text" name="username" placeholder="请输入用户名(6-20个字符)"/></div>
        <div><strong>个性描述:</strong><input type="text" name="desc" placeholder="最多10个字符"/></div>
        <div><strong>邮箱:</strong><input type="text" name="email" placeholder="邮箱"/></div>
        <div><strong>身高:</strong><input type="text" name="height" placeholder="身高(170-180)"/></div>
        <div><strong>年龄:</strong><input type="text" name="age" placeholder="年龄"/></div>
        <div><strong>性别枚举:</strong><input type="text" name="gender_enum" placeholder="性别（m|f）"/></div>
        <div>
                <strong>性别:</strong>
                <label for="gender_male">
                    <input type="radio" id="gender_male" value="m" name="gender" required>男
                </label>
                <label for="gender_female">
                    <input type="radio" id="gender_female" value="f" name="gender">女
                </label>
        </div>
        <div><strong>密码:</strong><input type="password" name="password" placeholder="请输入密码（最少6个字符）"/></div>
        <div><strong>确认密码:</strong><input type="password" name="password_confirm" placeholder="确认密码"/></div>
        <div>
            <strong>验证码:</strong><input type="text" name="vcode" placeholder="请输入密码"/>
            <img id="vcode_image" src="/demo/vcode"  width="75" height="20"  alt="验证码"  align="bottom" style="cursor:pointer;" title="看不清可单击图片刷新" " />
        </div>
    </fieldset>
    <div><input action-type="login" type="submit" value="登录"/></div>
</form>
</div>
<?php
    \Http\View\Tpl::loadView('comm/footer.phtml', [], $this);
    //加载js代码
    //\Http\View\Tpl::loadJs(['a.js']);
?>
